spring.application.name=unimag-leisure-inventory


# Base de datos
# TODO: colocar esto en variables de entorno
spring.datasource.url=jdbc:postgresql://localhost:5432/unimag_leisure
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=unimag_leisure_inventory_secret_key_2026_very_long_secure
jwt.expiration=86400000

# OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method

# Scheduled tasks
spring.task.scheduling.pool.size=5